# Generated by Django 5.1.5 on 2025-02-06 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='monthly_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='weekly_workouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
