# Generated by Django 5.1.5 on 2025-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userstats_monthly_progress_userstats_weekly_workouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='monthly_progress',
        ),
        migrations.AddField(
            model_name='userstats',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='last_workout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='monthly_workouts',
            field=models.IntegerField(default=0),
        ),
    ]
